import { env } from "cloudflare:workers";
import { ensureVideoReviewSchema } from "../../../db";

export const dynamic = "force-dynamic";
const BASE_URL="https://www.upmee.cc";

function config(){const apiKey=process.env.UPMEE_API_KEY?.trim(),cookie=process.env.UPMEE_SESSION_COOKIE?.trim(),teamId=process.env.UPMEE_TEAM_ID?.trim();return{apiKey,cookie,teamId,configured:Boolean(apiKey&&cookie&&teamId)};}
async function jsonOf(response:Response){const text=await response.text();try{return JSON.parse(text) as Record<string,unknown>;}catch{return{message:text};}}
async function post(path:string,headers:Record<string,string>,body:unknown){const response=await fetch(`${BASE_URL}${path}`,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(body),cache:"no-store"});const payload=await jsonOf(response);if(!response.ok)throw new Error(String(payload.message||payload.msg||"飞星数据请求失败"));return payload;}
function asNumber(value:unknown){const number=Number(value||0);return Number.isFinite(number)?number:0;}
function taskData(payload:Record<string,unknown>){const data=(payload.data&&typeof payload.data==="object"?payload.data:payload) as Record<string,unknown>;return Array.isArray(data.list)?data.list as Record<string,unknown>[]:[];}
function trendPoints(payload:Record<string,unknown>){const rows=Array.isArray(payload.trend_data)?payload.trend_data as Record<string,unknown>[]:[];const retention=rows.find(row=>Number(row.trend_type)===1)||rows[0];return Array.isArray(retention?.data)?(retention.data as Record<string,unknown>[]).map(point=>({second:asNumber(point.second),percentage:asNumber(point.percentage)})):[];}
function diagnose(metrics:Record<string,unknown>,retention:{second:number;percentage:number}[]){const play=asNumber(metrics.play),duration=Math.max(1,asNumber(metrics.duration)),full=asNumber(metrics.full_video_watched_rate),average=asNumber(metrics.average_time_watched);const engagement=(asNumber(metrics.digg)+asNumber(metrics.comment)+asNumber(metrics.share)+asNumber(metrics.favorite))/Math.max(1,play);let bestStart=0,bestEnd=Math.min(1,duration),smallestDrop=Infinity,worstStart=0,worstEnd=Math.min(1,duration),largestDrop=-1;for(let index=1;index<retention.length;index++){const drop=retention[index-1].percentage-retention[index].percentage;if(drop<smallestDrop){smallestDrop=drop;bestStart=retention[index-1].second;bestEnd=retention[index].second;}if(drop>largestDrop){largestDrop=drop;worstStart=retention[index-1].second;worstEnd=retention[index].second;}}const strengths:string[]=[],risks:string[]=[];if((retention.find(point=>point.second>=1)?.percentage||0)>=.75)strengths.push("首秒留存稳定，开头画面具备吸引力");else risks.push("首秒流失偏快，需要强化第一画面的结果感或冲突");if(full>=.3)strengths.push("完整观看率较好，内容节奏能够支撑结尾");else risks.push("完整观看率偏低，需压缩中段重复信息");if(engagement>=.03)strengths.push("互动率较高，内容具有讨论或收藏价值");else risks.push("互动反馈偏弱，卖点证明与评论引导需要加强");if(average/duration>=.55)strengths.push("平均观看覆盖过半，主体信息承接有效");else risks.push("平均观看时长不足一半，核心卖点出现位置可能过晚");return{engagement,averageRatio:average/duration,bestWindow:{start:bestStart,end:bestEnd,drop:smallestDrop===Infinity?0:smallestDrop},largestDrop:{start:worstStart,end:worstEnd,drop:largestDrop<0?0:largestDrop},strengths,risks};}

export async function GET(request:Request){const {apiKey,cookie,teamId,configured}=config();if(!configured||!apiKey||!cookie||!teamId)return Response.json({configured:false,error:"数据复盘服务尚未完成配置"},{status:503});const days=Math.min(90,Math.max(7,Number(new URL(request.url).searchParams.get("days")||7)));try{await ensureVideoReviewSchema();const headers={"API-Key":apiKey};let allTasks:Record<string,unknown>[]=[];for(let page=1;page<=4;page++){const payload=await post("/open_api/media/task/list",headers,{team_id:Number(teamId),page,page_size:50,pub_video_filter:"team",pub_time_filter:-1});const rows=taskData(payload);allTasks.push(...rows);if(rows.length<50)break;}const now=Date.now(),start=now-days*86400000,recent30Start=now-30*86400000;const recent30Count=allTasks.filter(task=>asNumber(task.pub_time||task.create_time)>=recent30Start).length;const tasks=allTasks.filter(task=>asNumber(task.pub_time||task.create_time)>=start&&String(task.state).includes("success"));const sources:{taskId:string;title:string;video:string;cover:string;publishedAt:number;mediaId:string;mediaName:string;mediaType:string;itemId:string}[]=[];for(const task of tasks){for(const media of (Array.isArray(task.medias)?task.medias:[]) as Record<string,unknown>[]){const itemId=String(media.item_id||"");if(!itemId)continue;sources.push({taskId:String(task.task_id||""),title:String(task.title||"未命名视频"),video:String(task.video||""),cover:String(task.cover||""),publishedAt:asNumber(task.pub_time||task.create_time),mediaId:String(media.media_id||""),mediaName:String(media.name||""),mediaType:String(media.media_type||""),itemId});}}
    const cookieHeaders={Cookie:cookie,Origin:BASE_URL,Referer:`${BASE_URL}/`};
    const items=[] as Record<string,unknown>[];
    for(let offset=0;offset<sources.length;offset+=4){const group=sources.slice(offset,offset+4);const resolved=await Promise.all(group.map(async source=>{const body={team_id:teamId,media_id:source.mediaId,item_ids:[source.itemId]};const [metricPayload,trendPayload]=await Promise.all([post("/api/media/item/metrics",cookieHeaders,body),post("/api/media/item/trend",cookieHeaders,body)]);const stats=Array.isArray(metricPayload.stats)?metricPayload.stats as Record<string,unknown>[]:[];const metrics=stats.find(row=>String(row.item_id)===source.itemId)||stats[0]||{};const retention=trendPoints(trendPayload);const analysis=diagnose(metrics,retention);const previous=await env.DB.prepare("SELECT metrics_json FROM video_metric_snapshots WHERE item_id = ? ORDER BY captured_at DESC LIMIT 1").bind(source.itemId).first<{metrics_json:string}>();let previousMetrics:Record<string,unknown>={};try{previousMetrics=previous?JSON.parse(previous.metrics_json):{};}catch{}const deltas={play:asNumber(metrics.play)-asNumber(previousMetrics.play),digg:asNumber(metrics.digg)-asNumber(previousMetrics.digg),comment:asNumber(metrics.comment)-asNumber(previousMetrics.comment),share:asNumber(metrics.share)-asNumber(previousMetrics.share),favorite:asNumber(metrics.favorite)-asNumber(previousMetrics.favorite)};return{...source,metrics,retention,analysis,deltas};}));items.push(...resolved);}
    const capturedAt=new Date().toISOString();if(items.length){await env.DB.batch(items.map(item=>env.DB.prepare("INSERT INTO video_metric_snapshots (id,item_id,media_id,task_id,title,media_name,video_url,cover_url,published_at,metrics_json,trend_json,captured_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(`${item.itemId}:${Date.now()}:${crypto.randomUUID()}`,item.itemId,item.mediaId,item.taskId,item.title,item.mediaName,item.video,item.cover,item.publishedAt,JSON.stringify(item.metrics),JSON.stringify(item.retention),capturedAt)));}
    const ranked=items.map(item=>{const metrics=item.metrics as Record<string,unknown>,analysis=item.analysis as {engagement:number;averageRatio:number};const score=Math.log10(asNumber(metrics.play)+10)*18+asNumber(metrics.full_video_watched_rate)*35+analysis.engagement*180+analysis.averageRatio*20;return{...item,score};}).sort((a,b)=>Number(b.score)-Number(a.score));const totals=ranked.reduce((sum,item)=>{const metrics=item.metrics as Record<string,unknown>;sum.play+=asNumber(metrics.play);sum.digg+=asNumber(metrics.digg);sum.comment+=asNumber(metrics.comment);sum.share+=asNumber(metrics.share);sum.favorite+=asNumber(metrics.favorite);return sum;},{play:0,digg:0,comment:0,share:0,favorite:0});const daily=Array.from({length:days},(_,index)=>{const dayStart=start+index*86400000,dayEnd=dayStart+86400000,dayItems=ranked.filter(item=>Number(item.publishedAt)>=dayStart&&Number(item.publishedAt)<dayEnd);return{date:new Date(dayStart).toISOString().slice(5,10),published:dayItems.length,play:dayItems.reduce((sum,item)=>sum+asNumber((item.metrics as Record<string,unknown>).play),0)};});return Response.json({configured:true,days,capturedAt,recent30Count,summary:{published:ranked.length,...totals,engagementRate:(totals.digg+totals.comment+totals.share+totals.favorite)/Math.max(1,totals.play)},daily,items:ranked},{headers:{"Cache-Control":"private, no-store"}});
  }catch(error){return Response.json({configured:true,error:error instanceof Error?error.message:"数据复盘读取失败"},{status:502});}}

export async function POST(request:Request){try{await ensureVideoReviewSchema();const payload=await request.json() as {days?:number;report?:unknown};const now=Date.now(),days=Math.min(90,Math.max(7,Number(payload.days||7))),start=now-days*86400000,id=`WR-${new Date().toISOString().slice(0,10)}-${crypto.randomUUID().slice(0,8)}`;await env.DB.prepare("INSERT INTO video_weekly_reports (id,range_start,range_end,report_json,created_at) VALUES (?,?,?,?,?)").bind(id,start,now,JSON.stringify(payload.report||{}),new Date().toISOString()).run();return Response.json({id,saved:true});}catch(error){return Response.json({error:error instanceof Error?error.message:"周报保存失败"},{status:500});}}
