import { desc, eq } from "drizzle-orm";
import { ensureContentPlanSchema, ensureSourceAssetSchema, getDb } from "../../../db";
import { contentTasks, sourceAssets } from "../../../db/schema";

type Candidate={id?:string;platform?:string;author?:string;title?:string;link?:string;embedUrl?:string;likes?:number;views?:number|null;comments?:number;favorites?:number;shares?:number};
type Classification={sourceId?:string;fitScore?:number;decision?:string;contentCategory?:string;hookType?:string;structureType?:string;conversionType?:string;recommendedAnalysisMode?:string;language?:string;marketFit?:string;reason?:string;tags?:string[];duplicateOf?:string};
type CollectorPayload={id?:string;taskId?:string;planId?:string;result?:Record<string,unknown>&{classifications?:Classification[]};candidates?:Candidate[]};
function parse<T>(value:string,fallback:T){try{return JSON.parse(value) as T;}catch{return fallback;}}
function toAsset(row:typeof sourceAssets.$inferSelect){return{id:row.id,taskId:row.taskId,planId:row.planId,sourceId:row.sourceId,platform:row.platform,title:row.title,author:row.author,link:row.link,embedUrl:row.embedUrl,metrics:parse(row.metricsJson,{}),classification:parse(row.classificationJson,{}),fitScore:row.fitScore,decision:row.decision,status:row.status,agentJobId:row.agentJobId,createdAt:row.createdAt,updatedAt:row.updatedAt};}

export async function GET(request:Request){try{await ensureSourceAssetSchema();const taskId=new URL(request.url).searchParams.get("taskId")?.trim();const rows=taskId?await getDb().select().from(sourceAssets).where(eq(sourceAssets.taskId,taskId)).orderBy(desc(sourceAssets.fitScore)):await getDb().select().from(sourceAssets).orderBy(desc(sourceAssets.updatedAt)).limit(100);return Response.json({assets:rows.map(toAsset)},{headers:{"Cache-Control":"no-store"}});}catch(error){return Response.json({error:error instanceof Error?error.message:"素材库读取失败"},{status:500});}}

export async function POST(request:Request){try{await ensureSourceAssetSchema();const payload=await request.json() as CollectorPayload;if(!payload.id||!payload.taskId||!payload.planId||!payload.result)return Response.json({error:"素材分类任务资料不完整"},{status:400});const classifications=Array.isArray(payload.result.classifications)?payload.result.classifications:[],candidates=Array.isArray(payload.candidates)?payload.candidates:[];if(!classifications.length)return Response.json({error:"采集 Agent 没有返回分类结果"},{status:400});const now=new Date().toISOString();for(const classification of classifications){const candidate=candidates.find(item=>item.id===classification.sourceId);if(!candidate)continue;const values:typeof sourceAssets.$inferInsert={id:`${payload.taskId}:${candidate.id}`,taskId:payload.taskId,planId:payload.planId,sourceId:String(candidate.id),platform:String(candidate.platform||"未知平台"),title:String(candidate.title||"未命名素材"),author:String(candidate.author||"未知作者"),link:String(candidate.link||""),embedUrl:String(candidate.embedUrl||""),metricsJson:JSON.stringify({likes:candidate.likes||0,views:candidate.views??null,comments:candidate.comments||0,favorites:candidate.favorites||0,shares:candidate.shares||0}),classificationJson:JSON.stringify(classification),fitScore:Math.max(0,Math.min(100,Number(classification.fitScore)||0)),decision:String(classification.decision||"observe"),status:"classified",agentJobId:payload.id,createdAt:now,updatedAt:now};const{id:ignored,createdAt:ignoredCreated,...updates}=values;void ignored;void ignoredCreated;await getDb().insert(sourceAssets).values(values).onConflictDoUpdate({target:[sourceAssets.taskId,sourceAssets.sourceId],set:updates});}const rows=await getDb().select().from(sourceAssets).where(eq(sourceAssets.taskId,payload.taskId)).orderBy(desc(sourceAssets.fitScore));return Response.json({assets:rows.map(toAsset)});}catch(error){return Response.json({error:error instanceof Error?error.message:"素材分类结果保存失败"},{status:500});}}

export async function PATCH(request:Request){try{await ensureSourceAssetSchema();await ensureContentPlanSchema();const payload=await request.json() as {taskId?:string;assetIds?:string[]};if(!payload.taskId||!Array.isArray(payload.assetIds)||!payload.assetIds.length)return Response.json({error:"请至少选择一条素材入库"},{status:400});const now=new Date().toISOString();for(const id of payload.assetIds){await getDb().update(sourceAssets).set({status:"archived",updatedAt:now}).where(eq(sourceAssets.id,id));}await getDb().update(contentTasks).set({status:"assets_ready",updatedAt:now}).where(eq(contentTasks.id,payload.taskId));return Response.json({ok:true,archived:payload.assetIds.length});}catch(error){return Response.json({error:error instanceof Error?error.message:"素材入库失败"},{status:500});}}
